# Generated by Django 4.0.5 on 2022-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=15)),
                ('Discription', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=11)),
            ],
        ),
    ]
